/* aa-sdk/agent/aa_sysdefs.h */

/*
 * Copyright (c) 2014, Avaya Inc.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef AA_SYSDEFS_H
#define AA_SYSDEFS_H

#undef SYSDEF_INCLUDE_SSH
#undef SYSDEF_INCLUDE_SPBM
#undef SYSDEF_INCLUDE_MLT
#undef SYSDEF_INCLUDE_FA_SMLT
#undef SYSDEF_INCLUDE_FLAGSHIP_STACKMANAGER
#undef SYSDEF_INCLUDE_NSX

#define SYSDEF_PLATFORM_ERS 1
#define SYSDEF_PLATFORM_SDK 2
#define SYSDEF_PLATFORM SYSDEF_PLATFORM_SDK

#endif /* ndef AA_SYSDEFSF_H */
